CREATE TABLE reports_logs (
    report_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    report_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    report_content VARCHAR2(4000),
    CONSTRAINT pk_reports_logs PRIMARY KEY (report_id)
);
/

CREATE OR REPLACE PACKAGE report_pkg IS
  PROCEDURE create_report(p_start IN TIMESTAMP);
  PROCEDURE create_report;
END report_pkg;
/

CREATE OR REPLACE PACKAGE BODY report_pkg AS

  last_report_time TIMESTAMP := TO_TIMESTAMP('1900-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS');

  PROCEDURE create_report(p_start IN TIMESTAMP) IS
    v_ins_customers NUMBER;
    v_upd_customers NUMBER;
    v_del_customers NUMBER;
    v_ins_orders    NUMBER;
    v_upd_orders    NUMBER;
    v_del_orders    NUMBER;
    v_ins_items     NUMBER;
    v_upd_items     NUMBER;
    v_del_items     NUMBER;
    v_report        VARCHAR2(4000);
  BEGIN
    SELECT COUNT(*) INTO v_ins_customers
      FROM audit_log
      WHERE table_name = 'CUSTOMERS'
        AND operation_type = 'I'
        AND change_time >= p_start;
    SELECT COUNT(*) INTO v_upd_customers
      FROM audit_log
      WHERE table_name = 'CUSTOMERS'
        AND operation_type = 'U'
        AND change_time >= p_start;
    SELECT COUNT(*) INTO v_del_customers
      FROM audit_log
      WHERE table_name = 'CUSTOMERS'
        AND operation_type = 'D'
        AND change_time >= p_start;

    SELECT COUNT(*) INTO v_ins_orders
      FROM audit_log
      WHERE table_name = 'ORDERS'
        AND operation_type = 'I'
        AND change_time >= p_start;
    SELECT COUNT(*) INTO v_upd_orders
      FROM audit_log
      WHERE table_name = 'ORDERS'
        AND operation_type = 'U'
        AND change_time >= p_start;
    SELECT COUNT(*) INTO v_del_orders
      FROM audit_log
      WHERE table_name = 'ORDERS'
        AND operation_type = 'D'
        AND change_time >= p_start;

    SELECT COUNT(*) INTO v_ins_items
      FROM audit_log
      WHERE table_name = 'ORDER_ITEMS'
        AND operation_type = 'I'
        AND change_time >= p_start;
    SELECT COUNT(*) INTO v_upd_items
      FROM audit_log
      WHERE table_name = 'ORDER_ITEMS'
        AND operation_type = 'U'
        AND change_time >= p_start;
    SELECT COUNT(*) INTO v_del_items
      FROM audit_log
      WHERE table_name = 'ORDER_ITEMS'
        AND operation_type = 'D'
        AND change_time >= p_start;

    v_report := '<html><head><title>Отчет об изменениях</title></head><body>';
    v_report := v_report || '<h1>Отчет об изменениях с ' || TO_CHAR(p_start, 'YYYY-MM-DD HH24:MI:SS') || '</h1>';
    v_report := v_report || '<table border="1" cellspacing="0" cellpadding="4">';
    v_report := v_report || '<tr><th>Таблица</th><th>INSERT</th><th>UPDATE</th><th>DELETE</th></tr>';
    v_report := v_report || '<tr><td>CUSTOMERS</td><td>' || v_ins_customers || '</td><td>' || v_upd_customers || '</td><td>' || v_del_customers || '</td></tr>';
    v_report := v_report || '<tr><td>ORDERS</td><td>' || v_ins_orders || '</td><td>' || v_upd_orders || '</td><td>' || v_del_orders || '</td></tr>';
    v_report := v_report || '<tr><td>ORDER_ITEMS</td><td>' || v_ins_items || '</td><td>' || v_upd_items || '</td><td>' || v_del_items || '</td></tr>';
    v_report := v_report || '</table></body></html>';

    INSERT INTO reports_logs (report_date, report_content)
      VALUES (SYSTIMESTAMP, v_report);
    COMMIT;

    DBMS_OUTPUT.PUT_LINE(v_report);

    last_report_time := SYSTIMESTAMP;
  END create_report;

  PROCEDURE create_report IS
  BEGIN
    create_report(last_report_time);
  END create_report;

END report_pkg;
/